### ISSUE TITLE
Field names containing double underscores break queries

### ISSUE THREAD

**Issue by andywalz** [aeguana/PyFileMaker#13]
First, thank you, this is a great module, appreciate your efforts on it. Second, a question:

Is there a good reason that '__' is being replaced with '::' in _addDBParam()? See:
https://github.com/aeguana/PyFileMaker/blob/master/PyFileMaker/FMServer.py#L179

This is breaking queries of mine that include field names containing double underscores (e.g. my_field__name eventually becomes my_field%3A%3Aname in the fmi/xml url)

**Comment by kawa-marcin** [comment]
Well, it was done to translate `obiect__field` to `object::field` in the query dict. It is used during the search etc, where you can reference fields this way.
Unfortunately this change will break the backward compatibility so can not be patched it the master.

Exaple:
```python
>> fm.doFind( {'documentID__op':'lt', '-max':1})
```

There are two choices, rename your fields with `__` or use your patched version and keep it up to date with original master.

Thanks

**Comment by andywalz** [comment]
Ok, thank you for the explanation. I likely will maintain a patched version.
