### ISSUE TITLE
doScript only returns first result

### ISSUE THREAD

**Issue by oldblivion** [aeguana/PyFileMaker#14]
In `FMServer.py` on line 245 the library makes the assumption that the script's first result will be the only useful result. There is the case where a user requires more than one result. 

Is this intended by design?

cc @nickw444
```python
	def doScript(self, script_name, params=None):
		"""This function executes the script for given layout for the current db."""
		request = [
			uu({'-db': self._db }),
			uu({'-lay': self._layout }),
			uu({'-script': script_name})
		]

		if params:
			request.append(uu({'-script.param': params }))

		request.append(uu({'-findall': '' }))

		result = self._doRequest(request)
		result = FMResultset.FMResultset(result)

		try:
			resp = result.resultset[0] # Try to return latest result
		except IndexError:
			resp = None

		return resp
```

**Comment by kawa-marcin** [comment]
Hi, thanks for pointing that out. This was initially done as a workaround for a huge resultsets being returned, but it doesn't make sense to force returning only the latest result. Unfortunately for backward compatibility full resultset is returned only if an extra argument `return_all` is passed.

Refer to: https://github.com/aeguana/PyFileMaker/commit/cd6de7ad961e7248cc72c6dc80c5cc16496f1728
