### ISSUE TITLE
Can files be sent to Filemaker

### ISSUE THREAD

**Issue by tremby** [aeguana/PyFileMaker#15]
I [see](https://github.com/aeguana/PyFileMaker/tree/master/Examples#retrieve-files) that files can be retrieved, but can they also be sent?

**Comment by kawa-marcin** [comment]
I think FileMaker XML API doesn't have support for creating files through the API. I might be wrong here but can not find any useful information about this feature.

FM XML API spec: https://fmhelp.filemaker.com/docs/15/en/fms15_cwp_guide.pdf

**Comment by maxwellk2** [comment]
AFAIK, FileMaker's CWP (Custom Web Publishing) system does not support a method to insert a file into a container (binary) field, and it's generally recommended to store an external reference. Don't think it can even be done with [FileMaker's own PHP API](https://www.filemaker.com/support/product/docs/12/fms/fms12_cwp_php_en.pdf). There may be a server-side method, or have a look at [Insert From URL](https://www.filemaker.com/help/15/fmp/en/index.html#page/FMP_Help/insert-from-url.html).

**Comment by tremby** [comment]
OK. Thanks very much.
