### ISSUE TITLE
hostnames with dash (-) are detected as not correctly formatted

### ISSUE THREAD

**Issue by basictheprogram** [aeguana/PyFileMaker#2]
Host names with dashes (-) are detected as not correctly formatted.
```
$ python
Python 2.7.10 (default, Jul 14 2015, 19:46:27)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyFileMaker import FMServer
>>> fm = FMServer('user:pass@host-1.domain.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
raise FMError, "Address of FileMaker Server is not correctly formatted"
PyFileMaker.FMError.FMError: Address of FileMaker Server is not correctly formatted
```
Tested this with our FileMaker servers which are named filemaker-1.domain.com, filemaker-2.domain.com, etc... 

I'm the network guy so I do not know if there's a non-dashed hostname requirement on FileMaker hostnames. But we've been using dashed host names since FileMaker 12 release.

**Comment by basictheprogram** [comment]
As convoluted as it gets, regex for hostnames and associated discussion.

http://stackoverflow.com/questions/1418423/the-hostname-regex

**Comment by kawa-marcin** [comment]
Yep, dashes should be accepted in the hostnames. Fix already pushed to master.
Cheers
