### ISSUE TITLE
FMServer.py:_doRequest() and 404 response

### ISSUE THREAD

**Issue by basictheprogram** [aeguana/PyFileMaker#4]
Using FMServer.getDBNames() and I'm getting a thrown exception  "<class 'xml.parsers.expat.ExpatError'> no element found: line 1, column 0"

The FileMaker developer changed something and the server is still listening on port 80 but this request is returning a 404 response at FMServer.py(668)_doRequest().

Request
```
http://fmserver:80//fmi/xml/fmresultset.xml?-dbnames=
```
Response
```
<Response [404]>
```
The problem is you don't get a thrown exception until xml2obj.py(104)ParseString() and the details says no element found: line 1, column 0 which is misleading.

Shouldn't there be a check in FMServer(339):getDBNames() to check the return value from _doRequest() before attempting to parse the ResultSet?

**Comment by basictheprogram** [comment]
http://stackoverflow.com/questions/15258728/requests-how-to-tell-if-youre-getting-a-404
```
>>> r = requests.get('http://httpbin.org/status/404')
>>> r.raise_for_status()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "requests/models.py", line 664, in raise_for_status
    raise http_error
requests.exceptions.HTTPError: 404 Client Error: NOT FOUND
>>> r = requests.get('http://httpbin.org/status/200')
>>> r.raise_for_status()
>>> # no exception raised.
```
Going to see how this works in FMServer._doRequest()

**Comment by kawa-marcin** [comment]
Merged
